name: awsl
description: A new Flutter project.
version: 2.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  english_words: ^4.0.0
  http: ^0.13.4
  fluttertoast: ^8.0.8
  extended_image: ^4.0.0
  image_gallery_saver: '^1.7.1'
  url_launcher: ^6.0.15
  wakelock: ^0.5.6

  dio: ^4.0.0
  json_annotation: 3.1.1

  cached_network_image: 3.0.0
  flutter_staggered_grid_view: 0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
